### ISSUE TITLE
Move to IPFS org?

### ISSUE THREAD

**Issue by daviddias** [haadcode/ipfs-daemon#8]

**Comment by haadcode** [comment]
In order to not have multiple ways of creating an ipfs instance, and given the new init API for js-ipfs, I want to deprecate this module. 

It was originally created to have an easy way to start and 1-to-1 API for both js-ipfs and go-ipfs as well as to have a way to use a dev version of go-ipfs-dep in order to pull in 0.4.5 (pubsub) back in the days. We've since released official go-ipfs version with pubsub, we've started to change the init API in js land and pubsub is now available through a shared API. The only thing preventing to deprecate this is to have a way to start/control go-ipfs daemon (ipfsd-ctl) through the same init API as js-ipfs now has.

In any case, we should deprecate this as soon as possible. I've added a big note to the [README](https://github.com/haadcode/ipfs-daemon) mentioning this.

Closing this issue as `wont't fix` :) Ie. let's not move to ipfs org but get rid of the module completely. Feel free to re-open if you disagree or want to discuss further.
